version: '3'

services: 
  render-server:
    build: ./renderer
    ports:
    - 8081:80
  editor-client:
    build: ./editor
    ports:
    - 8080:80
    environment: 
    - redis=sessions
  sessions:
    image: redis:5-alpine