version: '3'

services:
  render-server:
    build: ./renderer
  editor-client:
    build: ./editor
    ports:
      - 8080:80
    environment:
      - redis=sessions
      - renderer=render-server
  sessions:
    image: redis:5-alpine